platform :ios, '7.0'

pod 'AFNetworking', '~> 2.0'
pod 'ReactiveCocoa',          '~> 2.5'
#pod 'Reachability',             '~> 3.2'
#pod 'JSONKit-NoWarning',        '~> 1.2'
pod 'SDWebImage',               '~> 3.7.3'
#pod 'SDWebImage-ProgressView',  '~> 0.4.0'
pod 'MBProgressHUD',            '~> 0.9.1'
pod 'MJRefresh',                '~> 2.4.12'
#pod 'SWTableViewCell',          '~> 0.3.7'
#pod 'FMDB',                     '~> 2.5'
pod 'WebViewJavascriptBridge', '~> 4.1.5'
pod 'NJKWebViewProgress'